(defproject zeichnen "0.1.0-SNAPSHOT"
  :description "A Clojure program to animate the plotting of data generated by https://github.com/pwhittin/zauberon."
  :url "https://github.com/pwhittin/zeichnen"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url  "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.10.1"]
                 [org.clojure/tools.cli "1.0.194"]
                 [quil "3.1.0"]]
  :plugins [[lein-ancient "0.6.15"]
            [lein-cljfmt "0.6.7"]]
  :repl-options {:init-ns zeichnen.core}
  :main zeichnen.core
  :target-path "target/%s"
  ;:omit-source true
  :profiles {:uberjar {:aot :all}})
